### ISSUE TITLE
Сформулировать пользовательские истории

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/-2-#14]
Изучить лекцию
Use case-user stories.pdf

**Comment by Aleks-Nos** [comment]
сформировано: 
Я как преподаватель хочу иметь возможность видеть результаты студентов чтобы следить за успеваемостью и степенью освоения материала.
Я как преподаватель хочу иметь практические задание в курсе чтобы проверять степень усвоения материала студентом.
 
Я как компания ювелирсофта хочу иметь проработанный курс и заинтересовывающий студентов курс по 1с, чтобы привлечь новые кандидатов в компанию.
 
Я как администрация хочу иметь ресурс для быстрого сбора статистики по прохождению студентами курса, чтобы иметь информацию о всех студентах и их успеваемости
Я как администрация хочу иметь курс развивающий в студентах новые знания и навыки ...

Я как студент хочу иметь курс с теоретическими знаниями, применяемые в реальном проекте, который я могу воплотить самостоятельно, чтобы видеть, что знания полученные в курсе могут использоваться в реальном проекте.
Я как студент хочу иметь в итоге своей работы готовый продукт, чтобы получить интерактивный отклик от труда и пользоваться .
