### ISSUE TITLE
Нарисовать диаграмму вариант использования

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/-2-#15]
Изучить лекции:

1. Use Case.pdf
2. Используйте case-user stories.pdf

**Comment by Aleks-Nos** [comment]
Выполнил описание и диаграмму использования
https://drive.google.com/file/d/1Sx_43rieqCeFu2i74bezA0vPxl5QKw2a/view?usp=sharing
https://docs.google.com/spreadsheets/d/1xz0TNRjHYgxIo8v6HxNFSj-GtZKpecOOytg2EH8IPrM/edit?usp=sharing
